apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  type: ClusterIP
  selector:
    app: messaging-app
    version: blue # << Start by sending traffic to blue
  ports:
    - port: 80
      targetPort: 8000
